workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
    when: never
  - if: $CI_COMMIT_BRANCH

stages:
- build
- update-manifests

variables:
  APP_NAME: "backend-service-"
  DOCKER_IMAGE: ""
  DOCKER_FILE_NAME: ""
  MANIFEST_STAGING_PATH: ""
  COMMIT_MESSAGE: ""

# hidden jobs that can be reuse over other jobs 

.docker_build:
  image: docker:24.0.7
  stage: build
  before_script:
  - docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
  script:
  - docker  build -t $DOCKER_IMAGE  -f $DOCKER_FILE_NAME .
  - docker push $DOCKER_IMAGE


# .update_manifest:
#   stage: update-manifests
#   variables:
#     MANIFEST_GIT_REPO: https://$USERNAME:$PAT_TOKEN@git.gebeya.training/order-optima/k8s-manifests.git

#   before_script:
#   - apk add git
#   - git clone $MANIFEST_GIT_REPO
#   - git config --global user.name "$GITLAB_USER_NAME"
#   - git config --global user.email "$GITLAB_USER_EMAIL"
#   script:
#   - cd k8s-manifests
#   - git remote set-url origin --push $MANIFEST_GIT_REPO
#   - |
#     sed -i "s#image:.*#image: ${DOCKER_IMAGE}#g" ./$MANIFEST_STAGING_PATH
#   - git stage ./$MANIFEST_STAGING_PATH
#   - git commit -m "$COMMIT_MESSAGE [skip-ci]"
#   - git push origin HEAD:$CI_COMMIT_REF_NAME



.update_manifest:
  stage: update-manifests
  variables:
    MANIFEST_GIT_REPO: https://$USERNAME:$PAT_TOKEN@git.gebeya.training/order-optima/k8s-manifests.git

  before_script:
  - apk add git

  script:
    # Attempt to clone the repository with retry logic
  - |
    for i in {1..3}; do
      git clone $MANIFEST_GIT_REPO || continue
      break
    done
  
  - git config --global user.name "$GITLAB_USER_NAME"
  -  git config --global user.email "$GITLAB_USER_EMAIL"
  -  cd k8s-manifests

    # Set image name using environment variable (replace 'IMAGE_NAME' with actual variable name)
  - |
    export IMAGE_NAME=${DOCKER_USER_NAME}/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHA

    # Use sed with caution, consider alternative templating tools
  - |
    sed -i "s#image:.*#image: $IMAGE_NAME#g" ./$MANIFEST_STAGING_PATH

  -  git stage ./$MANIFEST_STAGING_PATH
  -  git commit -m "$COMMIT_MESSAGE [skip-ci]"
  -  git push origin HEAD:$CI_COMMIT_REF_NAME


build_apigateway_service:
  extends: .docker_build
  stage: build
  variables:
    DOCKER_FILE_NAME: "Dockerfile.api"
    IMAGE_PATH: "apiservice-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHA
build_service_discovery:
  extends: .docker_build
  stage: build
  variables:
    DOCKER_FILE_NAME: "Dockerfile.discovery"
    IMAGE_PATH: "servicediscovery-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHA

build_auth_service:
  extends: .docker_build
  stage: build
  variables:
    DOCKER_FILE_NAME: "Dockerfile.auth"
    IMAGE_PATH: "authservice-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHA

build_inventory_service:
  extends: .docker_build
  stage: build
  variables:
    DOCKER_FILE_NAME: "Dockerfile.inventory"
    IMAGE_PATH: "inventoryservice-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHA

build_order_service:
  extends: .docker_build
  stage: build
  variables:
    DOCKER_FILE_NAME: "Dockerfile.order"
    IMAGE_PATH: "orderservice-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHA

build_user_service:
  extends: .docker_build
  stage: build
  variables:
    DOCKER_FILE_NAME: "Dockerfile.user"
    IMAGE_PATH: "userservice-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHA

# update k8s manifest jobs 

# update_apigateway_manifest:
#   extends: .update_manifest
#   stage: update-manifests
#   variables:
#     MANIFEST_STAGING_PATH: "api-gateway/deployment.yaml"
#     COMMIT_MESSAGE: "update service managmanet image"
#     IMAGE_PATH: "apiservice-"
#     DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHA


update_apigateway_manifest:
  extends: .update_manifest
  stage: update-manifests
  variables:
    MANIFEST_STAGING_PATH: "api-gateway/deployment.yaml"
    COMMIT_MESSAGE: "update service management image"
    IMAGE_PATH: "apiservice-"

update_service_discovery_manifest:
  extends: .update_manifest
  stage: update-manifests
  variables:
    MANIFEST_STAGING_PATH: "service-discovery/deployment.yaml"
    COMMIT_MESSAGE: "update service managmanet image"
    IMAGE_PATH: "servicediscovery-"
    # DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHA

update_order_service_manifest:
  extends: .update_manifest
  stage: update-manifests
  variables:
    MANIFEST_STAGING_PATH: "order-management/deployment.yaml"
    COMMIT_MESSAGE: "update order  managmanet image"
    IMAGE_PATH: "orderservice-"
    # DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHA


update_inventory_service_manifest:
  extends: .update_manifest
  stage: update-manifests
  variables:
    MANIFEST_STAGING_PATH: "inventory-management/deployment.yaml"
    COMMIT_MESSAGE: "update order  inventory image"
    IMAGE_PATH: "inventoryservice-"
    # DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHA



update_auth_service-manifest:
  extends: .update_manifest
  stage: update-manifests
  variables:
    MANIFEST_STAGING_PATH: "auth-service/deployment.yaml"
    COMMIT_MESSAGE: "update auth service image"

    IMAGE_PATH: "authservice-"
    # DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHA
    
update_user_service-manifest:
  extends: .update_manifest
  stage: update-manifests
  variables:
    MANIFEST_STAGING_PATH: "user-service/deployment.yaml"
    COMMIT_MESSAGE: "update auth service image"

    IMAGE_PATH: "userservice-"
    # DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHA
