
spring:

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthenticationFilter




        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: inventory-managment
          # uri: lb://Inventory_Management
          uri: lb://inventory-managment
          
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthenticationFilter
            # - Path=/api/v1/category/**
            





  application:
    # name: API-GATEWAY
    name: api-service

eureka:
  client:
    service-url:
      defaultZone : http://${DISCOVERY}:8761/eureka
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/




server:
  port: 8181