
spring:

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: inventory-management
          uri: lb://inventory-management
          predicates:
            - Path=/api/v1/products/**
            - Path=/api/v1/product/**
            - Path=/api/v1/category/**
          filters:
            - AuthenticationFilter




  application:
    name: api-service

eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
  client:
    service-url:
      defaultZone : http://${DISCOVERY}:8761/eureka


server:
  port: 8181