
spring:

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthenticationFilter




        - id: Auth-Service
          uri: lb://Auth-Service
          predicates:
            - Path=/api/v1/auth/**

        - id: Inventory_Management
          uri: lb://Inventory_Management
          predicates:
            - Path=/api/v1/products/**
            # - Path=/api/v1/category/**
            





  application:
    name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://service-discovery:8761/eureka
      # defaultZone : http://localhost:8761/eureka


server:
  port: 8181