
spring:
  application:
    name: service-discovery

server:
  port: 8761

eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
    
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
#       # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/




