spring:
  application:
    name: User-Service

  datasource:
    driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/orderoptima
    url: jdbc:postgresql://postgres:5432/orderoptima
    username: postgres
    password: Kill

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



#Service Discovery
eureka:
  client:
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka
      defaultZone : http://service-discovery:8761/eureka

server:
  port: 7000
