spring:
  application:
    name: user-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    # bootstrap-servers: localhost:9092
    bootstrap-servers: broker:9092


#Service Discovery
eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
  client:
    serviceUrl:
       defaultZone: http://${DISCOVERY}:8761/eureka
      #  defaultZone : https://discovery-orderoptima.gebeyalearning.com



server:
  port: 7000

afroMessage:
  token: eyJhbGciOiJIUzI1NiJ9.eyJpZGVudGlmaWVyIjoiSDJlYXlmNllnTFFFSTJpeDBWNDNPTEFYYjFaZ24wRTciLCJleHAiOjE4Njc5MjA2MDQsImlhdCI6MTcxMDE1NDIwNCwianRpIjoiMTgzYmIwYjItNDM1ZS00ZjAwLWEwNzItMzZjZjU4YjNjZGI4In0.ho7JGfwoB7SjhE7h4Wlq0_sz0Nu3sHPgvW6iAbyvyHg
  baseUrl: https://api.afromessage.com/api/send

inventory:
  service:
    base:
      url: http://localhost:8181
