spring:
  application:
    # name: User-Service
    name: user-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



#Service Discovery
eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
  client:
    serviceUrl:
       defaultZone: http://${DISCOVERY}:8761/eureka



server:
  port: 7000
