spring:
  application:
    name: order-service


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone : http://${DISCOVERY}:8761/eureka



server:
  port: 0

management:
  tracing:
    sampling:
      probability: 1.0

afroMessage:
  token: eyJhbGciOiJIUzI1NiJ9.eyJpZGVudGlmaWVyIjoiSDJlYXlmNllnTFFFSTJpeDBWNDNPTEFYYjFaZ24wRTciLCJleHAiOjE4Njc5MjA2MDQsImlhdCI6MTcxMDE1NDIwNCwianRpIjoiMTgzYmIwYjItNDM1ZS00ZjAwLWEwNzItMzZjZjU4YjNjZGI4In0.ho7JGfwoB7SjhE7h4Wlq0_sz0Nu3sHPgvW6iAbyvyHg
  baseUrl: https://api.afromessage.com/api/send

logging:
  level:
    web: debug